import { Property } from './property';

export const propertyData: Property[] = [
  // {
  //   propertyId: '1',
  //   title: 'Luxury Apartment',
  //   address: 'Bangalore, India',
  //   price: 25000,
  //   description: '3BHK',
  //   carpetArea: 1200,
  //   ageOfBuilding: 2,
  //   availableStatus: 'Available',
  //   furnishedStatus: 'Fully Furnished',
  //   imgUrl: '/assets/new1.jpg',
  // },
  // {
  //   propertyId: '2',
  //   title: 'Cozy House',
  //   address: 'Mumbai, India',
  //   price: 35000,
  //   description: '2BHK',
  //   carpetArea: 1500,
  //   ageOfBuilding: 5,
  //   availableStatus: 'Occupied',
  //   furnishedStatus: 'Semi Furnished',
  //   imgUrl: '/assets/new2.jpg',
  // },
  // {
  //   propertyId: '3',
  //   title: 'Cozy House',
  //   address: 'Mumbai, India',
  //   price: 35000,
  //   description: '2BHK',
  //   carpetArea: 1500,
  //   ageOfBuilding: 5,
  //   availableStatus: 'Occupied',
  //   furnishedStatus: 'Semi Furnished',
  //   imgUrl: '/assets/new2.jpg',
  // },
  // {
  //   propertyId: '4',
  //   title: 'Cozy House',
  //   address: 'Mumbai, India',
  //   price: 35000,
  //   description: '2BHK',
  //   carpetArea: 1500,
  //   ageOfBuilding: 5,
  //   availableStatus: 'Occupied',
  //   furnishedStatus: 'Semi Furnished',
  //   imgUrl: '/assets/new2.jpg',
  // },
];
