/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Property } from "./components/dashboard-page/property-listing/property";
export { Property } from "./components/dashboard-page/property-listing/property";
export namespace Components {
    interface AddPropertyForm {
        "source": string;
        "user": number;
    }
    interface AppNavbar {
        "role": string;
    }
    interface AppRoutes {
    }
    interface DashboardPage {
    }
    interface InquiryForm {
        "propertyId": string | number;
        "showForm": boolean;
    }
    interface InquiryPage {
        "role": string;
    }
    interface LoginPage {
    }
    interface OwnerProperties {
        "user": number;
    }
    interface PaymentsPage {
        "role": string;
        "userId": number;
    }
    interface PropertyCard {
        "bookingStatus": boolean;
        "propertys": Property;
        "role": string;
    }
    interface PropertyListing {
        "listingProperties"?: Property[];
        "source"?: string;
        "user"?: number;
    }
    interface TenantFavorites {
    }
    interface UserProfile {
        "role": string;
        "user": number;
    }
}
export interface AddPropertyFormCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAddPropertyFormElement;
}
export interface AppNavbarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAppNavbarElement;
}
export interface InquiryFormCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLInquiryFormElement;
}
export interface OwnerPropertiesCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLOwnerPropertiesElement;
}
export interface PropertyCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPropertyCardElement;
}
declare global {
    interface HTMLAddPropertyFormElement extends Components.AddPropertyForm, HTMLStencilElement {
    }
    var HTMLAddPropertyFormElement: {
        prototype: HTMLAddPropertyFormElement;
        new (): HTMLAddPropertyFormElement;
    };
    interface HTMLAppNavbarElement extends Components.AppNavbar, HTMLStencilElement {
    }
    var HTMLAppNavbarElement: {
        prototype: HTMLAppNavbarElement;
        new (): HTMLAppNavbarElement;
    };
    interface HTMLAppRoutesElement extends Components.AppRoutes, HTMLStencilElement {
    }
    var HTMLAppRoutesElement: {
        prototype: HTMLAppRoutesElement;
        new (): HTMLAppRoutesElement;
    };
    interface HTMLDashboardPageElement extends Components.DashboardPage, HTMLStencilElement {
    }
    var HTMLDashboardPageElement: {
        prototype: HTMLDashboardPageElement;
        new (): HTMLDashboardPageElement;
    };
    interface HTMLInquiryFormElement extends Components.InquiryForm, HTMLStencilElement {
    }
    var HTMLInquiryFormElement: {
        prototype: HTMLInquiryFormElement;
        new (): HTMLInquiryFormElement;
    };
    interface HTMLInquiryPageElement extends Components.InquiryPage, HTMLStencilElement {
    }
    var HTMLInquiryPageElement: {
        prototype: HTMLInquiryPageElement;
        new (): HTMLInquiryPageElement;
    };
    interface HTMLLoginPageElement extends Components.LoginPage, HTMLStencilElement {
    }
    var HTMLLoginPageElement: {
        prototype: HTMLLoginPageElement;
        new (): HTMLLoginPageElement;
    };
    interface HTMLOwnerPropertiesElement extends Components.OwnerProperties, HTMLStencilElement {
    }
    var HTMLOwnerPropertiesElement: {
        prototype: HTMLOwnerPropertiesElement;
        new (): HTMLOwnerPropertiesElement;
    };
    interface HTMLPaymentsPageElement extends Components.PaymentsPage, HTMLStencilElement {
    }
    var HTMLPaymentsPageElement: {
        prototype: HTMLPaymentsPageElement;
        new (): HTMLPaymentsPageElement;
    };
    interface HTMLPropertyCardElement extends Components.PropertyCard, HTMLStencilElement {
    }
    var HTMLPropertyCardElement: {
        prototype: HTMLPropertyCardElement;
        new (): HTMLPropertyCardElement;
    };
    interface HTMLPropertyListingElement extends Components.PropertyListing, HTMLStencilElement {
    }
    var HTMLPropertyListingElement: {
        prototype: HTMLPropertyListingElement;
        new (): HTMLPropertyListingElement;
    };
    interface HTMLTenantFavoritesElement extends Components.TenantFavorites, HTMLStencilElement {
    }
    var HTMLTenantFavoritesElement: {
        prototype: HTMLTenantFavoritesElement;
        new (): HTMLTenantFavoritesElement;
    };
    interface HTMLUserProfileElement extends Components.UserProfile, HTMLStencilElement {
    }
    var HTMLUserProfileElement: {
        prototype: HTMLUserProfileElement;
        new (): HTMLUserProfileElement;
    };
    interface HTMLElementTagNameMap {
        "add-property-form": HTMLAddPropertyFormElement;
        "app-navbar": HTMLAppNavbarElement;
        "app-routes": HTMLAppRoutesElement;
        "dashboard-page": HTMLDashboardPageElement;
        "inquiry-form": HTMLInquiryFormElement;
        "inquiry-page": HTMLInquiryPageElement;
        "login-page": HTMLLoginPageElement;
        "owner-properties": HTMLOwnerPropertiesElement;
        "payments-page": HTMLPaymentsPageElement;
        "property-card": HTMLPropertyCardElement;
        "property-listing": HTMLPropertyListingElement;
        "tenant-favorites": HTMLTenantFavoritesElement;
        "user-profile": HTMLUserProfileElement;
    }
}
declare namespace LocalJSX {
    interface AddPropertyForm {
        "onPageRender"?: (event: AddPropertyFormCustomEvent<string>) => void;
        "source"?: string;
        "user"?: number;
    }
    interface AppNavbar {
        "onHandleNav"?: (event: AppNavbarCustomEvent<string>) => void;
        "role"?: string;
    }
    interface AppRoutes {
    }
    interface DashboardPage {
    }
    interface InquiryForm {
        "onCloseForm"?: (event: InquiryFormCustomEvent<void>) => void;
        "propertyId"?: string | number;
        "showForm"?: boolean;
    }
    interface InquiryPage {
        "role"?: string;
    }
    interface LoginPage {
    }
    interface OwnerProperties {
        "onChangeNav"?: (event: OwnerPropertiesCustomEvent<string>) => void;
        "user"?: number;
    }
    interface PaymentsPage {
        "role"?: string;
        "userId"?: number;
    }
    interface PropertyCard {
        "bookingStatus"?: boolean;
        "onAddToFavorites"?: (event: PropertyCardCustomEvent<{ favorite: boolean; property: Property }>) => void;
        "onBooking"?: (event: PropertyCardCustomEvent<{ booked: boolean; property: Property }>) => void;
        "propertys": Property;
        "role"?: string;
    }
    interface PropertyListing {
        "listingProperties"?: Property[];
        "source"?: string;
        "user"?: number;
    }
    interface TenantFavorites {
    }
    interface UserProfile {
        "role"?: string;
        "user"?: number;
    }
    interface IntrinsicElements {
        "add-property-form": AddPropertyForm;
        "app-navbar": AppNavbar;
        "app-routes": AppRoutes;
        "dashboard-page": DashboardPage;
        "inquiry-form": InquiryForm;
        "inquiry-page": InquiryPage;
        "login-page": LoginPage;
        "owner-properties": OwnerProperties;
        "payments-page": PaymentsPage;
        "property-card": PropertyCard;
        "property-listing": PropertyListing;
        "tenant-favorites": TenantFavorites;
        "user-profile": UserProfile;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "add-property-form": LocalJSX.AddPropertyForm & JSXBase.HTMLAttributes<HTMLAddPropertyFormElement>;
            "app-navbar": LocalJSX.AppNavbar & JSXBase.HTMLAttributes<HTMLAppNavbarElement>;
            "app-routes": LocalJSX.AppRoutes & JSXBase.HTMLAttributes<HTMLAppRoutesElement>;
            "dashboard-page": LocalJSX.DashboardPage & JSXBase.HTMLAttributes<HTMLDashboardPageElement>;
            "inquiry-form": LocalJSX.InquiryForm & JSXBase.HTMLAttributes<HTMLInquiryFormElement>;
            "inquiry-page": LocalJSX.InquiryPage & JSXBase.HTMLAttributes<HTMLInquiryPageElement>;
            "login-page": LocalJSX.LoginPage & JSXBase.HTMLAttributes<HTMLLoginPageElement>;
            "owner-properties": LocalJSX.OwnerProperties & JSXBase.HTMLAttributes<HTMLOwnerPropertiesElement>;
            "payments-page": LocalJSX.PaymentsPage & JSXBase.HTMLAttributes<HTMLPaymentsPageElement>;
            "property-card": LocalJSX.PropertyCard & JSXBase.HTMLAttributes<HTMLPropertyCardElement>;
            "property-listing": LocalJSX.PropertyListing & JSXBase.HTMLAttributes<HTMLPropertyListingElement>;
            "tenant-favorites": LocalJSX.TenantFavorites & JSXBase.HTMLAttributes<HTMLTenantFavoritesElement>;
            "user-profile": LocalJSX.UserProfile & JSXBase.HTMLAttributes<HTMLUserProfileElement>;
        }
    }
}
